# Generated by Django 5.1.5 on 2025-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(default='0 RUB', max_length=10)),
            ],
        ),
    ]
